>>> a.data
{'a': 1}
>>> d.data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'data'
